-- Sets up and loads CMS DE-SynPUF Inpatient Claims Sample 1 into MySQL
-- Run once. Source: CMS Synthetic Public Use Files, 2008-2010 sample.

CREATE DATABASE claims_practice;
USE claims_practice;

CREATE TABLE inpatient_claims (
  `DESYNPUF_ID` VARCHAR(20),
  `CLM_ID` VARCHAR(20),
  `SEGMENT` INT,
  `CLM_FROM_DT` VARCHAR(8),
  `CLM_THRU_DT` VARCHAR(8),
  `PRVDR_NUM` VARCHAR(20),
  `CLM_PMT_AMT` DECIMAL(10,2),
  `NCH_PRMRY_PYR_CLM_PD_AMT` DECIMAL(10,2),
  `AT_PHYSN_NPI` VARCHAR(20),
  `OP_PHYSN_NPI` VARCHAR(20),
  `OT_PHYSN_NPI` VARCHAR(20),
  `CLM_ADMSN_DT` VARCHAR(8),
  `ADMTNG_ICD9_DGNS_CD` VARCHAR(15),
  `CLM_PASS_THRU_PER_DIEM_AMT` DECIMAL(10,2),
  `NCH_BENE_IP_DDCTBL_AMT` DECIMAL(10,2),
  `NCH_BENE_PTA_COINSRNC_LBLTY_AM` DECIMAL(10,2),
  `NCH_BENE_BLOOD_DDCTBL_LBLTY_AM` DECIMAL(10,2),
  `CLM_UTLZTN_DAY_CNT` DECIMAL(10,2),
  `NCH_BENE_DSCHRG_DT` VARCHAR(8),
  `CLM_DRG_CD` VARCHAR(10),
  `ICD9_DGNS_CD_1` VARCHAR(15),
  `ICD9_DGNS_CD_2` VARCHAR(15),
  `ICD9_DGNS_CD_3` VARCHAR(15),
  `ICD9_DGNS_CD_4` VARCHAR(15),
  `ICD9_DGNS_CD_5` VARCHAR(15),
  `ICD9_DGNS_CD_6` VARCHAR(15),
  `ICD9_DGNS_CD_7` VARCHAR(15),
  `ICD9_DGNS_CD_8` VARCHAR(15),
  `ICD9_DGNS_CD_9` VARCHAR(15),
  `ICD9_DGNS_CD_10` VARCHAR(15),
  `ICD9_PRCDR_CD_1` VARCHAR(15),
  `ICD9_PRCDR_CD_2` VARCHAR(15),
  `ICD9_PRCDR_CD_3` VARCHAR(15),
  `ICD9_PRCDR_CD_4` VARCHAR(15),
  `ICD9_PRCDR_CD_5` VARCHAR(15),
  `ICD9_PRCDR_CD_6` VARCHAR(15),
  `HCPCS_CD_1` VARCHAR(15),
  `HCPCS_CD_2` VARCHAR(15),
  `HCPCS_CD_3` VARCHAR(15),
  `HCPCS_CD_4` VARCHAR(15),
  `HCPCS_CD_5` VARCHAR(15),
  `HCPCS_CD_6` VARCHAR(15),
  `HCPCS_CD_7` VARCHAR(15),
  `HCPCS_CD_8` VARCHAR(15),
  `HCPCS_CD_9` VARCHAR(15),
  `HCPCS_CD_10` VARCHAR(15),
  `HCPCS_CD_11` VARCHAR(15),
  `HCPCS_CD_12` VARCHAR(15),
  `HCPCS_CD_13` VARCHAR(15),
  `HCPCS_CD_14` VARCHAR(15),
  `HCPCS_CD_15` VARCHAR(15),
  `HCPCS_CD_16` VARCHAR(15),
  `HCPCS_CD_17` VARCHAR(15),
  `HCPCS_CD_18` VARCHAR(15),
  `HCPCS_CD_19` VARCHAR(15),
  `HCPCS_CD_20` VARCHAR(15),
  `HCPCS_CD_21` VARCHAR(15),
  `HCPCS_CD_22` VARCHAR(15),
  `HCPCS_CD_23` VARCHAR(15),
  `HCPCS_CD_24` VARCHAR(15),
  `HCPCS_CD_25` VARCHAR(15),
  `HCPCS_CD_26` VARCHAR(15),
  `HCPCS_CD_27` VARCHAR(15),
  `HCPCS_CD_28` VARCHAR(15),
  `HCPCS_CD_29` VARCHAR(15),
  `HCPCS_CD_30` VARCHAR(15),
  `HCPCS_CD_31` VARCHAR(15),
  `HCPCS_CD_32` VARCHAR(15),
  `HCPCS_CD_33` VARCHAR(15),
  `HCPCS_CD_34` VARCHAR(15),
  `HCPCS_CD_35` VARCHAR(15),
  `HCPCS_CD_36` VARCHAR(15),
  `HCPCS_CD_37` VARCHAR(15),
  `HCPCS_CD_38` VARCHAR(15),
  `HCPCS_CD_39` VARCHAR(15),
  `HCPCS_CD_40` VARCHAR(15),
  `HCPCS_CD_41` VARCHAR(15),
  `HCPCS_CD_42` VARCHAR(15),
  `HCPCS_CD_43` VARCHAR(15),
  `HCPCS_CD_44` VARCHAR(15),
  `HCPCS_CD_45` VARCHAR(15)
);


LOAD DATA LOCAL INFILE '/Users/douglas/downloads/DE1_0_2008_to_2010_Inpatient_Claims_Sample_1.csv'
INTO TABLE inpatient_claims
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- After running LOAD DATA above, immediately run SHOW WARNINGS LIMIT 50;
-- in a separate query to inspect any conversion issues before proceeding.